### ISSUE TITLE
The function "g_memdup2" gets implicitly declared.

### ISSUE THREAD

**Issue by ohno9119** [cafe-desktop/ctk#20]
Hi, I am the guy who recently emailed you about potentially collaborating. I am now porting the changes from my fork to CTK, but I discovered this issue when compiling.

**Comment by ohno9119** [comment]
I am currently working on a PR for fixing this.

**Comment by sc0w** [comment]
seems `GLib 2.67.3` is required

See https://gitlab.gnome.org/GNOME/glib/-/commit/5bc9710fa644115b39bcc6fbed3b44397fd5bfa5

**Comment by ohno9119** [comment]
Instead of forcing, GLib 2.67.3 or higher, I have implemented a fallback for compiling on older versions of GLib.

**Comment by sc0w** [comment]
GLib 2.67.3 was released 2 years ago (Feb 4, 2021), I think is time enough to force it.

**Comment by sc0w** [comment]
now, since https://github.com/cafe-desktop/ctk/commit/a300cbff5e98f211b9c3f3e7d816d7d107720abf + https://github.com/cafe-desktop/ctk/commit/88a35758d0b0c7e536e2a593f0bc37fa22eae47c + https://github.com/cafe-desktop/ctk/commit/6240e86b8eada00b3945ec29188a25b35f9f6af6 + https://github.com/cafe-desktop/ctk/commit/06ef8bb9b95362c7dc6abd066d9908d69c8ef090 + https://github.com/cafe-desktop/ctk/commit/e09905da879de5ac0195ec6de3f1498b8f5f9e31 you the build must be ok in debian bullseye
